### PR TITLE
add `—release` in "Build From Source" example

### PR DESCRIPTION
**Pull request by nicolaiunrein**
I think this is important for people without a Rust background.

### CODE REVIEW

**Comment by arijit79** [comment]
As you are trying to improve the section, you should probably describe what tools are required to build it and also very shortly tell what each step does

**Comment by nicolaiunrein** [comment]
Do you mean something like:
```
# with cargo installed run
$ cargo build —release
```

Sorry, I don’t quite understand what you mean. My point is that building in release mode is what people want in 99% of the cases after cloning.

**Comment by nicolaiunrein** [comment]
Also I think its more convenient for rustaceans. If you are like me I would forget the release flag in 9/10 cases when copy pasting this snippet.

**Comment by arijit79** [comment]
I was trying to say something like this, you should state this:-

"In order to build binserve from source", you need the following requirements

* Git
* Rust
* Cargo
* A C linker"

Then you can put the already present commands here. Finally you can add this to the end of the section

"The first command will install the sources from GitHub, the next command moves into the downloaded project folder. Finally the last command builds the actual program"

**Review by mufeedvh — APPROVED** [review]
Nice PR @nicolaiunrein! :heart::clap:

Also, I've noted what @arijit79 stated, I will add more instructions to the **Build From Source** section. :+1: 

Thank You @nicolaiunrein @arijit79! :heart::raised_hands:

**Pull request merged**
